### ISSUE TITLE
login as  superadmin

### ISSUE THREAD

**Issue by darshanan24** [weihanchen/user-authentication-nodejs#2]
Hi, 
could you explain to me how to login as superadmin?  
I followed the steps, 
First I initialized roles in the database, by going to this URL:http://localhost:3000/#/api/initialize.
Second : i registered as guest, i am able to login, but when i put superadmin as username and password, its giving error, [object Object]. Please provide instructions on how to login as superadmin in your app? 

Thanks, 
Darshan

![image](https://user-images.githubusercontent.com/27047823/48400966-d3666000-e74d-11e8-8d2f-7f1facfc455c.png)

**Comment by weihanchen** [comment]
When you post: `localhost:3000/api/initialize` shoud response:
```json
{
    "success": true,
    "message": "Successful initialize."
}
```

Check if your database has a user record with `superadmin`.

Is there more log?

node version: `v7.1.0`

Thanks

**Comment by darshanan24** [comment]
Hey, I got this response in POSTMAN, Is there any way to login as superadmin in UI? If there isn't, how to edit the role of a user and delete the user using CLI?

**Comment by darshanan24** [comment]
Node version -v9.2.0

for normal user, how to change his password?

![image](https://user-images.githubusercontent.com/27047823/48471247-7afc9480-e819-11e8-85c7-f24e246cdb37.png)

for normal user after loggin in it gives JWT token right?  How to use that Jwt tokens in POSTMAN?
![image](https://user-images.githubusercontent.com/27047823/48475170-332e3b00-e822-11e8-86ae-b4e39a17fde1.png) .

**Comment by weihanchen** [comment]
Any console log in browser? 

Use that Jwt tokens in POSTMAN
![screenshot from 2018-11-15 08-21-53](https://user-images.githubusercontent.com/8265812/48521654-661f1000-e8b0-11e8-90bc-80f3b4851d56.png)
